FROM ghcr.io/routine/rails:3.0@sha256:0a4260434432b87b44bc379dc8b87d5b927afeb2a7638cc67cba74c09c6bd67d

RUN apk add --no-cache \
  build-base python3 less git \
  postgresql-dev \
  nodejs-current npm yarn
