FROM ghcr.io/routine/rails:2.7@sha256:7fc99a3b3a76b8dfd2abc7c9abed83a83127f5bc7ad332ac5b2068f5ef0b8493

RUN apk add --no-cache \
  build-base python3 less git \
  postgresql-dev \
  nodejs-current npm yarn
